return {
	"NeotestPassed",
	"NeotestFailed",
	"NeotestRunning",
	"NeotestSkipped",
	"NeotestTest",
	"NeotestNamespace",
	"NeotestFocused",
	"NeotestFile",
	"NeotestDir",
	"NeotestIndent",
	"NeotestExpandMarker",
	"NeotestAdapterName",
	"NeotestWinSelect",
	"NeotestMarked",
	"NeotestTarget",
	"NeotestUnknown",
}
