return {
	"RenderMarkdownH1Bg",
	"RenderMarkdownH2Bg",
	"RenderMarkdownH3Bg",
	"RenderMarkdownH4Bg",
	"RenderMarkdownH5Bg",
	"RenderMarkdownCode",
	"RenderMarkdownCodeInline",
	"RenderMarkdownBullet",
	"RenderMarkdownTableHead",
	"RenderMarkdownTableRow",
	"RenderMarkdownSuccess",
	"RenderMarkdownInfo",
	"RenderMarkdownHint",
	"RenderMarkdownWarn",
	"RenderMarkdownError",
}
