return {
	"TelescopeBorder",
	"TelescopeMatching",
	"TelescopeNormal",
	"TelescopeSelection",
	"TelescopeSelectionCaret",
	"TelescopePromptBorder",
	"TelescopePromptTitle",
	"TelescopePromptNormal",
	"TelescopePromptPrefix",
	"TelescopePreviewTitle",
	"TelescopePreviewBorder",
	"TelescopeResultsTitle",
	"TelescopeResultsBorder",
}
